apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec: 
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: djo26/frontend:1.0
        ports:
        - containerPort: 5000
        env:
        - name: USER_SERVICE
          value: "http://user-service:5001/users"
        - name: ORDER_SERVICE
          value: "http://order-service:5002/orders"

---
apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30080